### ISSUE TITLE
missing email-otp-spi-1.0-SNAPSHOT.war

### ISSUE THREAD

**Issue by althaf004** [richardjkendall/login-with-email#3]
i tried to implement this, but could see the folder target/email-otp-spi-1.0-SNAPSHOT.war is missing. could u please push that too ?

**Comment by richardjkendall** [comment]
Hi @althaf004 

I generally don't consider it good practice to include binary artifacts in my repositories.

If you want to build the war, you can run the following command

```
mvn clean package
```

**Comment by richardjkendall** [comment]
Closed as I've not heard back.
